name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: "Test with Jekyll ${{ matrix.jekyll }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        jekyll: ["~> 3.9", "~> 4.2"]
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install Dependencies
        run: bundle install
      - name: Make script/cibuild Executable
        run: chmod +x script/cibuild
      - name: Run Build Script
        run: script/cibuild
      - name: Build Jekyll Site
        run: bundle exec jekyll build -d docs/_site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: docs/_site
